### ISSUE TITLE
Deleted files when deleting an engine should go to the system's Recycle Bin

### ISSUE THREAD

**Issue by JadeJuno** [Funkin-Launcher-Team/FunkinLauncher#5]
Hey! So, I may've been an idiot, and assuming that the Launcher would create a folder in the folder I selected, tried to download VSlice on my Desktop. And when it didn't, I tried to delete it through the launcher, also assuming that the launcher would just delete the files that it knew where part of the game.
It didn't, and it tried to delete everything in my Desktop, until it met a file that couldn't get deleted for some reason (Probably permissions? Not sure.)

Anyways yeah, **please don't make your program just permanently delete files recursively, _thank you!_**

**Comment by toperri** [comment]
I'm so sorry for that! Implementation of the Trash Bin is too hard for the project. but regardless i'll make the user select their executable so that the launcher doesn't link vslice with the desktop.
